version: '3.7'
services:

  maple-testall-sql:
    container_name: maple-testall-sql
    build:
      context: ../.
      dockerfile: docker/sql.dockerfile
    image: maple-testall-sql
    networks:
      - maple
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

  maple-testall-redis:
    container_name: maple-testall-redis
    image: redis:7.2.3-alpine
    networks:
      - maple
    ports:
    - "6379:6379"

  maple-testall-minio:
    container_name: maple-testall-minio
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    networks:
      - maple
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
    - "9000:9000"
    command: "minio server /data"

networks:
  maple:
    name: maple